### PR TITLE
Custom marker pattern - Prototype

### PR DESCRIPTION
**Pull request by ghost**
Example to test the AR

### CODE REVIEW

**Review by sloumdrone — CHANGES_REQUESTED** [review]
Please link tot he lib version of aframe and move the html to test items. Then we'll get a route setup.

**Comment by ghost** [comment]
Changes for the correct pathing have been made

**Review by unleashalicia — COMMENTED** [review]
I am leaving this for Brian to approve file paths, but I definitely approve library patches.  Thanks, Cesca!  Looks great!

**Review by sloumdrone — APPROVED** [review]
Sounds good. Adding now.

**Pull request merged**
